### ISSUE TITLE
Effectiveness of entropy loss

### ISSUE THREAD

**Issue by 97littleleaf11** [dogyoonlee/DP-NeRF#1]
Hi! Thanks to your great work! 

I noticed that there exists some modifed `EntropyLoss` in your codebase which is not being used. Does it work in your experiments? It would be great if you could share your thoughts on it.

**Comment by dogyoonlee** [comment]
@97littleleaf11 
I experimented the `EntropyLoss` with my model when I tried to improve the performance.
The loss was not effective on my model.
In fact, the code is no more used in my project as you said.
I will remove the code with update. 
Thank you for your attention.
