### ISSUE TITLE
RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation

### ISSUE THREAD

**Issue by YellowTigerr** [dogyoonlee/DP-NeRF#4]
[TRAIN] Iter: 600 Loss: 0.023193560540676117  PSNR: 19.362762451171875 TIME: 0h:0m:40.74s
[TRAIN] Iter: 800 Loss: 0.01994657889008522  PSNR: 20.115781784057617 TIME: 0h:0m:53.53s
[TRAIN] Iter: 1000 Loss: 0.018907170742750168  PSNR: 20.629796981811523 TIME: 0h:1m:6.02s
Traceback (most recent call last):
  File "/DP-NeRF-main/run_dpnerf.py", line 753, in <module>
    train()
  File "/DP-NeRF-main/run_dpnerf.py", line 639, in train
    loss.backward()
  File "/lcy_DP/lib/python3.9/site-packages/torch/_tensor.py", line 396, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "/miniconda3/envs/lcy_DP/lib/python3.9/site-packages/torch/autograd/__init__.py", line 173, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.cuda.FloatTensor [512]], which is output 0 of LinalgVectorNormBackward0, is at version 1; expected version 0 instead. Hint: enable anomaly detection to find the operation that failed to compute its gradient, with torch.autograd.set_detect_anomaly(True).

训练到1000iter时报错，这个怎么解决呀.是pytorch版本问题吗。我的版本为pyorch==1.12.1

**Comment by dogyoonlee** [comment]
@YellowTigerr 
Thank you for your interest in our work.
It seems to be the problem of the library version.
Please check the installed version of the libraries.

I used 
torch 1.11.0+cu113
torchvision 0.12.0+cu113
