### ISSUE TITLE
training from my own data, the object in the photo disappears

### ISSUE THREAD

**Issue by xianrui-luo** [dogyoonlee/DP-NeRF#5]
Hi, I encounter a problem trying to deblur my own data.
the training data is like below:

the novel view is like this:

I wonder what is the problem, thank you. I only change the source directory, my data is the llff format.

**Comment by xianrui-luo** [comment]
I made a mistake for data loading, I apologize for the trouble.

**Comment by zkaiWu** [comment]
hi, I have the same problem.
Can you tell me how to solve it.
thanks.
