### ISSUE TITLE
Problem about llff dataset.

### ISSUE THREAD

**Issue by zkaiWu** [dogyoonlee/DP-NeRF#6]
I train dp-nerf on the blurred LLFF data ( generated by applying blur kernel), and resize the input to 252x188. The results are like this.
![010](https://github.com/dogyoonlee/DP-NeRF/assets/53325998/92138aa9-8274-4815-a3b8-2c3047f60c02)
![000](https://github.com/dogyoonlee/DP-NeRF/assets/53325998/8987a974-3e66-4176-8353-68772bf6e69d)
It seems like that the main obj in the image disappears, are there any parameters need to adjust with resolution?

**Comment by dogyoonlee** [comment]
I guess there is something mistake in data loading process.
Please refer the https://github.com/dogyoonlee/DP-NeRF/issues/5.
